install-docker:
  unless: :docker.in_executable_path?
  actions:
    - name: "Get file"
      shell: "Download docker.#{item}.tgz"
      with_items:
        - "x"
        - "y"

    - name: "Extract file"
      test: 'tar xf xyz item'
      with_items: '"xxxxxxxx".split("")'

provision-docker-storage:
  actions:
    - name: "one"
      shell: "rm -rf /"
      with_items:
        - "x"
        - "y"
