install-docker:
  unless: :docker.in_executable_path?
  actions:
    - name: "List dir"
      command: "/bin/ls -l #{item}"
      with_items:
        - "/"
        - "/home"

    - name: "Extract file"
      test: 'tar xf xyz #{item}'
      with_items: >
        "item1,item2,item3".split(",")

provision-docker-storage:
  actions:
    - name: "one"
      shell: "rm -rf /"
      with_items:
        - "x"
        - "y"
