install-docker:
  unless: :docker.in_executable_path?
  actions:
    - name: "Read items"
      command: "cat items"
      register: items

    - name: "Print item #{item}"
      test: "Printing #{item}"
      with_items: items["Result"]["stdout"].split("\n")

    - name: "Extract file"
      test: 'tar xf xyz #{item}'
      with_items: >
        "item1,item2,item3".split(",")

provision-docker-storage:
  actions:
    - name: "one"
      shell: "rm -rf /"
      with_items:
        - "x"
        - "y"
