install-docker:
  unless: :docker.in_executable_path?
  actions:
    - name: "Get file"
      shell: "Download docker.tgz"
      register: moobar

    - name: "Extract file"
      test: 'tar xf xyz #{item}'
      with_items: '"xxx".split("")'

provision-docker-storage:
  actions:
    - name: "one"
      shell: "rm -rf /"
      with_items:
        - "x"
        - "y"
